CREATE OR REPLACE VIEW APT_VW_OPERACOES_ORDEM_SLD AS
SELECT TO_NUMBER((DECODE(X.ORD_CH_STATUS, 'E',0,'F',1)||ROWNUM)) SEQ,
       X."ORG_TAB_IN_CODIGO",X."ORG_PAD_IN_CODIGO",X."ORG_IN_CODIGO",X."ORG_TAU_ST_CODIGO",X."FIL_IN_CODIGO",X."ORD_TAB_IN_CODIGO",X."ORD_SEQ_IN_CODIGO",X."ORD_IN_CODIGO",X."ORD_IN_CODIGO_PAI",X."ORD_IN_PRIORIDADE",X."ORD_DT_RECEBIMENTO",X."ORD_BO_CONTEM_ORDEM_FILHA",X."CLI_IN_CODIGO",X."ORD_ST_ALTERNATIVO",X."ORD_ST_SEMANA",X."GRU_ST_NOME",X."PRO_TAB_IN_CODIGO",X."PRO_PAD_IN_CODIGO",X."PRO_IN_CODIGO",X."PRO_ST_ALTERNATIVO",X."PRO_ST_DESCRICAO",X."PLF_IN_SQOPERACAO",X."PLF_IN_SQOPERACAO_PRI",X."PLF_IN_SQOPERACAO_ULT",X."POD_ST_SITUACAO",X."TMP_CH_APONTA",X."MAQ_IN_CODIGO",X."MAQ_ST_NOME",X."CEL_IN_CODIGO",X."CEL_ST_NOME",X."OPR_IN_CODIGO",X."POD_RE_QTDENECESSARIA",X."POD_RE_QTDEREAL",X."PLF_RE_QTDE_REFUGO_ACUM",X."PLF_RE_QTDE_SUBPROD_ACUM",X."ORD_RE_SALDO_OF",X."PRC_ST_DESCRICAO",X."APO_IN_SEQUENCIA_ANT",X."TPO_BO_RENDIMENTO",X."POD_BO_VALIDA_SALDO",X."CUS_BO_BLOQUEIA_SEQ_ORDEM",X."ORD_BO_LIB_SEQ",X."POD_BO_BLOQUEIA_APT_SEQ",X."ORD_CH_STATUS",X."APT_DT_INICIO",X."MAQ_CH_STATUS",X."POD_RE_QTDE_SALDO",X."POD_RE_TEMPOEXEC_PREV_TOT",X."POD_RE_TEMPOEXEC_PREV_UNIT",
       DECODE(X.ORD_CH_STATUS, 'E', 'EXECUÇÃO', 'F', 'FILA', 'O', 'OCORRÊNCIA')       AS ORD_ST_STATUS,
       DECODE(X.MAQ_CH_STATUS, 'E', 'EXECUÇÃO', 'O', 'OCORRÊNCIA', 'F', 'OCIOSIDADE') AS MAQ_ST_STATUS


FROM   (
				SELECT --ORDEM
							 SEQ.ORG_TAB_IN_CODIGO,
							 SEQ.ORG_PAD_IN_CODIGO,
							 SEQ.ORG_IN_CODIGO,
							 SEQ.ORG_TAU_ST_CODIGO,
							 SEQ.FIL_IN_CODIGO,
							 SEQ.ORD_TAB_IN_CODIGO,
							 SEQ.ORD_SEQ_IN_CODIGO,
							 SEQ.ORD_IN_CODIGO,
							 SEQ.ORD_IN_CODIGO_PAI,
							 ORD.ORD_IN_PRIORIDADE,
							 ORD.ORD_DT_RECEBIMENTO,
							 SEQ.ORD_BO_CONTEM_ORDEM_FILHA,
							 ORD.CLI_IN_CODIGO,
							 ORD.ORD_ST_ALTERNATIVO,

							 TO_CHAR(ORD.ORD_DT_RECEBIMENTO,'IW')||'-'||TO_CHAR(ORD.ORD_DT_RECEBIMENTO,'YYYY') ORD_ST_SEMANA,

							 --PRODUTO
							 ORD.GRU_ST_NOME,
							 ORD.PRO_TAB_IN_CODIGO,
							 ORD.PRO_PAD_IN_CODIGO,
							 ORD.PRO_IN_CODIGO,
							 ORD.PRO_ST_ALTERNATIVO,
							 ORD.PRO_ST_DESCRICAO,


							 --PROGRAMAÇÃO
							 SEQ.PLF_IN_SQOPERACAO,
							 SEQ.PLF_IN_SQOPERACAO_PRI,
							 SEQ.PLF_IN_SQOPERACAO_ULT,
							 SEQ.POD_ST_SITUACAO,
							 SEQ.TMP_CH_APONTA,
							 SEQ.MAQ_IN_CODIGO,
							 SEQ.MAQ_ST_NOME,
							 SEQ.CEL_IN_CODIGO,
							 SEQ.CEL_ST_NOME,
							 SEQ.OPR_IN_CODIGO,
							 SEQ.POD_RE_QTDENECESSARIA,
							 SEQ.POD_RE_QTDEREAL,
							 SEQ.PLF_RE_QTDE_REFUGO_ACUM,
							 SEQ.PLF_RE_QTDE_SUBPROD_ACUM,
							 SEQ.ORD_RE_SALDO_OF,
							 SEQ.PRC_ST_DESCRICAO,
               SEQ.APO_IN_SEQUENCIA_ANT,
							 SEQ.TPO_BO_RENDIMENTO,
							 CASE
							   WHEN SEQ.TPO_BO_RENDIMENTO = 'S' AND SEQ.PLF_IN_SQOPERACAO = SEQ.PLF_IN_SQOPERACAO_PRI THEN 'N'
								 ELSE 'S'
							 END POD_BO_VALIDA_SALDO,

							 --INDICA SE BLOQUEIA APONTAMENTO DE ORDEM FORA DA SEQUÊNCIA
							 SEQ.CUS_BO_BLOQUEIA_SEQ_ORDEM,

               --INDICA SE A ORDEM PERMITE APONTAMENTO FORA DA SEQUÊNCIA
							 SEQ.ORD_BO_LIB_SEQ,

							 --INDICA SE A OPERAÇÃO PERMITE APONTENTO FORA DE SEQUENCIAMENTO
							 CASE
							   WHEN SEQ.ORD_BO_LIB_SEQ            = 'S' THEN 'N'
								 WHEN SEQ.CUS_BO_BLOQUEIA_SEQ_ORDEM = 'S' AND SEQ.ORD_BO_LIB_SEQ = 'N' THEN 'S'
                 WHEN SEQ.CUS_BO_BLOQUEIA_SEQ_ORDEM = 'N' AND SEQ.ORD_BO_LIB_SEQ = 'N' THEN 'N'
                 WHEN SEQ.CUS_BO_BLOQUEIA_SEQ_ORDEM = 'S' AND SEQ.ORD_BO_LIB_SEQ = 'S' THEN 'N'
								 ELSE 'N'
							 END POD_BO_BLOQUEIA_APT_SEQ,

               --STATUS DA OPERAÇÃO
							 NVL((SELECT MIN(DECODE(ATI.ATI_CH_PRODUTIVA,'P','E','I','O'))
										FROM   MGCUSTOM.APT_APONTAORDEM APT,
										       MGMAN.PRO_ATIVIDADE      ATI
										WHERE  APT.ORG_TAB_IN_CODIGO = SEQ.ORG_TAB_IN_CODIGO
											AND  APT.ORG_PAD_IN_CODIGO = SEQ.ORG_PAD_IN_CODIGO
											AND  APT.ORG_IN_CODIGO     = SEQ.ORG_IN_CODIGO
											AND  APT.ORG_TAU_ST_CODIGO = SEQ.ORG_TAU_ST_CODIGO
											AND  APT.FIL_IN_CODIGO     = SEQ.FIL_IN_CODIGO
											AND  APT.ORD_TAB_IN_CODIGO = SEQ.ORD_TAB_IN_CODIGO
											AND  APT.ORD_SEQ_IN_CODIGO = SEQ.ORD_SEQ_IN_CODIGO
											AND  APT.ORD_IN_CODIGO     = SEQ.ORD_IN_CODIGO
											AND  APT.PLF_IN_SQOPERACAO = SEQ.PLF_IN_SQOPERACAO

											AND  APT.APT_ATI_IN_CODIGO = ATI.ATI_IN_CODIGO

											AND  APT.APT_CH_STATUS     = 'A'),'F') ORD_CH_STATUS,

               --STATUS DA OPERAÇÃO
							 NVL((SELECT MIN(APT.APT_DT_APONTAMENTO + (APT.APT_RE_TEMPOINICIAL/86400))
										FROM   MGCUSTOM.APT_APONTAORDEM APT
										WHERE  APT.ORG_TAB_IN_CODIGO = SEQ.ORG_TAB_IN_CODIGO
											AND  APT.ORG_PAD_IN_CODIGO = SEQ.ORG_PAD_IN_CODIGO
											AND  APT.ORG_IN_CODIGO     = SEQ.ORG_IN_CODIGO
											AND  APT.ORG_TAU_ST_CODIGO = SEQ.ORG_TAU_ST_CODIGO
											AND  APT.FIL_IN_CODIGO     = SEQ.FIL_IN_CODIGO
											AND  APT.ORD_TAB_IN_CODIGO = SEQ.ORD_TAB_IN_CODIGO
											AND  APT.ORD_SEQ_IN_CODIGO = SEQ.ORD_SEQ_IN_CODIGO
											AND  APT.ORD_IN_CODIGO     = SEQ.ORD_IN_CODIGO
											AND  APT.PLF_IN_SQOPERACAO = SEQ.PLF_IN_SQOPERACAO
											AND  APT.APT_CH_STATUS     = 'A'),NULL) APT_DT_INICIO,


               --VERIFICA SE HÁ OCORRÊNCIA ABERTA PARA O CENTRO DE TRBALHO
							 NVL((SELECT 'O'
										FROM   MGCUSTOM.APT_APONTAORDEM APT,
										       MGMAN.PRO_ATIVIDADE      ATI,
													 MGMAN.PRO_ORDENS         ORD
										WHERE  APT.ORG_TAB_IN_CODIGO = SEQ.ORG_TAB_IN_CODIGO
											AND  APT.ORG_PAD_IN_CODIGO = SEQ.ORG_PAD_IN_CODIGO
											AND  APT.ORG_IN_CODIGO     = SEQ.ORG_IN_CODIGO
											AND  APT.ORG_TAU_ST_CODIGO = SEQ.ORG_TAU_ST_CODIGO
											AND  APT.FIL_IN_CODIGO     = SEQ.FIL_IN_CODIGO
											AND  APT.APT_MAQ_IN_CODIGO = SEQ.MAQ_IN_CODIGO

										  AND  APT.ORG_TAB_IN_CODIGO = ORD.ORG_TAB_IN_CODIGO (+)
										  AND  APT.ORG_PAD_IN_CODIGO = ORD.ORG_PAD_IN_CODIGO (+)
										  AND  APT.ORG_IN_CODIGO     = ORD.ORG_IN_CODIGO     (+)
										  AND  APT.ORG_TAU_ST_CODIGO = ORD.ORG_TAU_ST_CODIGO (+)
										  AND  APT.FIL_IN_CODIGO     = ORD.FIL_IN_CODIGO     (+)
										  AND  APT.ORD_TAB_IN_CODIGO = ORD.ORD_TAB_IN_CODIGO (+)
										  AND  APT.ORD_SEQ_IN_CODIGO = ORD.ORD_SEQ_IN_CODIGO (+)
										  AND  APT.ORD_IN_CODIGO     = ORD.ORD_IN_CODIGO     (+)
										  AND  NVL(ORD.ORD_ST_SITUACAO,'X') NOT IN ('EN','CA')

											AND  APT.APT_ATI_IN_CODIGO = ATI.ATI_IN_CODIGO

											AND  ATI.ATI_CH_PRODUTIVA  = 'I'

											AND  APT.APT_CH_STATUS     = 'A'

											AND  ROWNUM                = 1),NVL((SELECT 'E'
																													 FROM   MGCUSTOM.APT_APONTAORDEM APT,
																																	MGMAN.PRO_ATIVIDADE      ATI,
																																	MGMAN.PRO_ORDENS         ORD
																													 WHERE  APT.ORG_TAB_IN_CODIGO = SEQ.ORG_TAB_IN_CODIGO
																														 AND  APT.ORG_PAD_IN_CODIGO = SEQ.ORG_PAD_IN_CODIGO
																														 AND  APT.ORG_IN_CODIGO     = SEQ.ORG_IN_CODIGO
																														 AND  APT.ORG_TAU_ST_CODIGO = SEQ.ORG_TAU_ST_CODIGO
																														 AND  APT.FIL_IN_CODIGO     = SEQ.FIL_IN_CODIGO
																														 AND  APT.APT_MAQ_IN_CODIGO = SEQ.MAQ_IN_CODIGO

																														 AND  APT.ORG_TAB_IN_CODIGO = ORD.ORG_TAB_IN_CODIGO (+)
																														 AND  APT.ORG_PAD_IN_CODIGO = ORD.ORG_PAD_IN_CODIGO (+)
																														 AND  APT.ORG_IN_CODIGO     = ORD.ORG_IN_CODIGO     (+)
																														 AND  APT.ORG_TAU_ST_CODIGO = ORD.ORG_TAU_ST_CODIGO (+)
																														 AND  APT.FIL_IN_CODIGO     = ORD.FIL_IN_CODIGO     (+)
																														 AND  APT.ORD_TAB_IN_CODIGO = ORD.ORD_TAB_IN_CODIGO (+)
																														 AND  APT.ORD_SEQ_IN_CODIGO = ORD.ORD_SEQ_IN_CODIGO (+)
																														 AND  APT.ORD_IN_CODIGO     = ORD.ORD_IN_CODIGO     (+)
																														 AND  NVL(ORD.ORD_ST_SITUACAO,'X') NOT IN ('EN','CA')

																														 AND  APT.APT_ATI_IN_CODIGO = ATI.ATI_IN_CODIGO

																														 AND  ATI.ATI_CH_PRODUTIVA  = 'P'

																														 AND  APT.APT_CH_STATUS     = 'A'

																														 AND  ROWNUM                = 1),'F')) MAQ_CH_STATUS,

							 --SALDO
							 --PRIMEIRA OPERAÇÃO
							 CASE
								 --PRIMEIRA OPERAÇÃO SEM DEPENDÊNCIA DE ORDEM FILHA
								 WHEN SEQ.PLF_IN_SQOPERACAO = SEQ.PLF_IN_SQOPERACAO_PRI AND SEQ.ORD_BO_CONTEM_ORDEM_FILHA = 'N' AND NVL(SEQ.CUS_BO_APTSALDO,'S') = 'N' THEN
											(SEQ.POD_RE_QTDENECESSARIA - (SEQ.POD_RE_QTDEREAL + SEQ.PLF_RE_QTDE_REFUGO_ACUM))

								 --PRIMEIRA OPERAÇÃO COM DEPENDÊNCIA DE ORDEM FILHA
								 WHEN SEQ.PLF_IN_SQOPERACAO = SEQ.PLF_IN_SQOPERACAO_PRI AND SEQ.ORD_BO_CONTEM_ORDEM_FILHA = 'S' AND NVL(SEQ.CUS_BO_APTSALDO,'S') = 'N' THEN
											(SEQ.ORD_RE_SALDO_OF  - (SEQ.POD_RE_QTDEREAL + SEQ.PLF_RE_QTDE_REFUGO_ACUM))

								 --QUALQUER OPERAÇÃO QUANDO PERMITE APONTAMENTO SEM VALIDAÇÃO DE SALDO DE OPERAÇÃO ANTERIOR
								 WHEN NVL(SEQ.CUS_BO_APTSALDO,'S') = 'S'                                                        THEN
                      (SEQ.POD_RE_QTDENECESSARIA - (SEQ.POD_RE_QTDEREAL + SEQ.PLF_RE_QTDE_REFUGO_ACUM))

								 --OUTRAS OPERAÇÕES
								 WHEN SEQ.PLF_IN_SQOPERACAO <> SEQ.PLF_IN_SQOPERACAO_PRI AND NVL(SEQ.CUS_BO_APTSALDO,'S') = 'N' THEN
								 			(SEQ.POD_RE_QTDE_REAL_ANT - (SEQ.POD_RE_QTDEREAL + SEQ.PLF_RE_QTDE_REFUGO_ACUM))

								 ELSE 0
							 END POD_RE_QTDE_SALDO,




							 --TEMPO TOTAL
							 TRIM(MGMAN.MAN_PCK_UTIL.F_CONVERTEHORAS(
																											 CASE
																												 WHEN SEQ.TMP_BO_TEMPOFIXO = 'S' THEN
																															SEQ.POD_RE_TEMPO_EXEC_PREV
																												 ELSE (SEQ.TMP_RE_QTDEEXEC/SEQ.TMP_RE_FATOREXEC) * (CASE
																																																						 --PRIMEIRA OPERAÇÃO SEM DEPENDÊNCIA DE ORDEM FILHA
																																																						 WHEN SEQ.PLF_IN_SQOPERACAO = SEQ.PLF_IN_SQOPERACAO_PRI AND SEQ.ORD_BO_CONTEM_ORDEM_FILHA = 'N' THEN
																																																									(SEQ.POD_RE_QTDENECESSARIA - (SEQ.POD_RE_QTDEREAL + SEQ.PLF_RE_QTDE_REFUGO_ACUM))

																																																						 --PRIMEIRA OPERAÇÃO COM DEPENDÊNCIA DE ORDEM FILHA
																																																						 WHEN SEQ.PLF_IN_SQOPERACAO = SEQ.PLF_IN_SQOPERACAO_PRI AND SEQ.ORD_BO_CONTEM_ORDEM_FILHA = 'S' THEN
																																																									(SEQ.ORD_RE_SALDO_OF  - (SEQ.POD_RE_QTDEREAL + SEQ.PLF_RE_QTDE_REFUGO_ACUM))
																																																						 --OUTRAS OPERAÇÕES
																																																						 ELSE
																																																								 (SEQ.POD_RE_QTDE_REAL_ANT - (SEQ.POD_RE_QTDEREAL + SEQ.PLF_RE_QTDE_REFUGO_ACUM))
																																																					 END)
																											 END)) POD_RE_TEMPOEXEC_PREV_TOT,

							 --TEMPO UNITÁRIO
							 TRIM(MGMAN.MAN_PCK_UTIL.F_CONVERTEHORAS(
																											 CASE
																												 WHEN SEQ.TMP_BO_TEMPOFIXO = 'S' THEN
																															SEQ.POD_RE_TEMPO_EXEC_PREV
																												 ELSE (SEQ.TMP_RE_QTDEEXEC/SEQ.TMP_RE_FATOREXEC)

																											 END)) POD_RE_TEMPOEXEC_PREV_UNIT


				FROM
						 MGCUSTOM.CUS_VW_ORDENS ORD,
						 --CONTROLE DE SALDOS
						 (
							SELECT
										 PO.ORG_TAB_IN_CODIGO,
										 PO.ORG_PAD_IN_CODIGO,
										 PO.ORG_IN_CODIGO,
										 PO.ORG_TAU_ST_CODIGO,
										 PO.ORD_TAB_IN_CODIGO,
										 PO.ORD_SEQ_IN_CODIGO,
										 PO.ORD_IN_CODIGO,
										 MGCUSTOM.CUS_F_ORDEM_PAI(PO.ORG_IN_CODIGO,PO.ORD_SEQ_IN_CODIGO,PO.ORD_IN_CODIGO) ORD_IN_CODIGO_PAI,
										 PO.FIL_IN_CODIGO,

										 PO.PLF_IN_SQOPERACAO,
										 PO.POD_ST_SITUACAO,
										 PO.TMP_CH_APONTA,
										 PO.MAQ_TAB_IN_CODIGO,
										 PO.MAQ_PAD_IN_CODIGO,
										 PO.MAQ_IN_CODIGO,
										 MAQ.MAQ_ST_NOME,
										 CEL.CEL_IN_CODIGO,
										 CEL.CEL_ST_NOME,
                     CMAQ.CUS_BO_APTSALDO,
										 NVL(CMAQ.CUS_BO_BLOQUEIA_SEQ_ORDEM,'N') CUS_BO_BLOQUEIA_SEQ_ORDEM,
										 NVL(OCE.ORD_BO_LIB_SEQ,'N')             ORD_BO_LIB_SEQ,

										 PO.OPR_TAB_IN_CODIGO,
										 PO.OPR_PAD_IN_CODIGO,
										 PO.OPR_IN_CODIGO,
										 PO.POD_RE_QTDENECESSARIA,

										 PO.POD_RE_TEMPO_EXEC_PREV,
										 PO.TMP_BO_TEMPOFIXO,
										 PO.TMP_RE_QTDEEXEC,
										 PO.TMP_RE_FATOREXEC,

										 PRC.PRC_ST_DESCRICAO,

										 TPO.TPO_BO_RENDIMENTO,

										 --IDENTIFICA A QTDE REALIZADA NA OPERAÇÃO
										 NVL((SELECT SUM(AO.APO_RE_QUANTIDADE)
													FROM   MGMAN.PRO_APONTAORDEM AO
													WHERE  AO.ORG_TAB_IN_CODIGO = PO.ORG_TAB_IN_CODIGO
														 AND AO.ORG_PAD_IN_CODIGO = PO.ORG_PAD_IN_CODIGO
														 AND AO.ORG_IN_CODIGO     = PO.ORG_IN_CODIGO
														 AND AO.ORG_TAU_ST_CODIGO = PO.ORG_TAU_ST_CODIGO
														 AND AO.FIL_IN_CODIGO     = PO.FIL_IN_CODIGO
														 AND AO.ORD_TAB_IN_CODIGO = PO.ORD_TAB_IN_CODIGO
														 AND AO.ORD_SEQ_IN_CODIGO = PO.ORD_SEQ_IN_CODIGO
														 AND AO.ORD_IN_CODIGO     = PO.ORD_IN_CODIGO
														 AND AO.PLF_IN_SQOPERACAO = PO.PLF_IN_SQOPERACAO
														 AND AO.UNI_TAB_IN_CODIGO = PO.UNI_TAB_IN_CODIGO
														 AND AO.UNI_PAD_IN_CODIGO = PO.UNI_PAD_IN_CODIGO
														 AND AO.UNI_ST_UNIDADE    = PO.UNI_ST_UNIDADE),0) POD_RE_QTDEREAL,

										 --IDENTIFICA A OPERAÇÃO ANTERIOR
										 (SELECT MAX(POA.PLF_IN_SQOPERACAO)
											FROM   MGMAN.PRO_PROG_ORDEM POA
											WHERE  POA.ORG_TAB_IN_CODIGO = PO.ORG_TAB_IN_CODIGO
												 AND POA.ORG_PAD_IN_CODIGO = PO.ORG_PAD_IN_CODIGO
												 AND POA.ORG_IN_CODIGO     = PO.ORG_IN_CODIGO
												 AND POA.ORG_TAU_ST_CODIGO = PO.ORG_TAU_ST_CODIGO
												 AND POA.FIL_IN_CODIGO     = PO.FIL_IN_CODIGO
												 AND POA.ORD_TAB_IN_CODIGO = PO.ORD_TAB_IN_CODIGO
												 AND POA.ORD_SEQ_IN_CODIGO = PO.ORD_SEQ_IN_CODIGO
												 AND POA.ORD_IN_CODIGO     = PO.ORD_IN_CODIGO
												 AND POA.TMP_CH_APONTA     = 'S'
												 AND POA.PLF_IN_SQOPERACAO < PO.PLF_IN_SQOPERACAO) PLF_IN_SQOPERACAO_ANT,

										 --IDENTIFICA A QTDE REALIZADA NA OPERAÇÃO ANTERIOR
										 NVL((SELECT SUM(APO.APO_RE_QUANTIDADE)
													FROM   MGMAN.PRO_PROG_ORDEM  POA,
																 MGMAN.PRO_APONTAORDEM APO
													WHERE  POA.ORG_TAB_IN_CODIGO = PO.ORG_TAB_IN_CODIGO
														 AND POA.ORG_PAD_IN_CODIGO = PO.ORG_PAD_IN_CODIGO
														 AND POA.ORG_IN_CODIGO     = PO.ORG_IN_CODIGO
														 AND POA.ORG_TAU_ST_CODIGO = PO.ORG_TAU_ST_CODIGO
														 AND POA.FIL_IN_CODIGO     = PO.FIL_IN_CODIGO
														 AND POA.ORD_TAB_IN_CODIGO = PO.ORD_TAB_IN_CODIGO
														 AND POA.ORD_SEQ_IN_CODIGO = PO.ORD_SEQ_IN_CODIGO
														 AND POA.ORD_IN_CODIGO     = PO.ORD_IN_CODIGO
														 AND POA.TMP_CH_APONTA     = 'S'

														 AND POA.ORG_TAB_IN_CODIGO = APO.ORG_TAB_IN_CODIGO
														 AND POA.ORG_PAD_IN_CODIGO = APO.ORG_PAD_IN_CODIGO
														 AND POA.ORG_IN_CODIGO     = APO.ORG_IN_CODIGO
														 AND POA.ORG_TAU_ST_CODIGO = APO.ORG_TAU_ST_CODIGO
														 AND POA.FIL_IN_CODIGO     = APO.FIL_IN_CODIGO
														 AND POA.ORD_TAB_IN_CODIGO = APO.ORD_TAB_IN_CODIGO
														 AND POA.ORD_SEQ_IN_CODIGO = APO.ORD_SEQ_IN_CODIGO
														 AND POA.ORD_IN_CODIGO     = APO.ORD_IN_CODIGO
														 AND POA.PLF_IN_SQOPERACAO = APO.PLF_IN_SQOPERACAO
														 AND POA.UNI_TAB_IN_CODIGO = APO.UNI_TAB_IN_CODIGO
														 AND POA.UNI_PAD_IN_CODIGO = APO.UNI_PAD_IN_CODIGO
														 AND POA.UNI_ST_UNIDADE    = APO.UNI_ST_UNIDADE

														 AND POA.PLF_IN_SQOPERACAO = (SELECT MAX(POA.PLF_IN_SQOPERACAO)
																													FROM   MGMAN.PRO_PROG_ORDEM POA
																													WHERE  POA.ORG_TAB_IN_CODIGO = PO.ORG_TAB_IN_CODIGO
																														 AND POA.ORG_PAD_IN_CODIGO = PO.ORG_PAD_IN_CODIGO
																														 AND POA.ORG_IN_CODIGO     = PO.ORG_IN_CODIGO
																														 AND POA.ORG_TAU_ST_CODIGO = PO.ORG_TAU_ST_CODIGO
																														 AND POA.FIL_IN_CODIGO     = PO.FIL_IN_CODIGO
																														 AND POA.ORD_TAB_IN_CODIGO = PO.ORD_TAB_IN_CODIGO
																														 AND POA.ORD_SEQ_IN_CODIGO = PO.ORD_SEQ_IN_CODIGO
																														 AND POA.ORD_IN_CODIGO     = PO.ORD_IN_CODIGO
																														 AND POA.TMP_CH_APONTA     = 'S'
																														 AND POA.PLF_IN_SQOPERACAO < PO.PLF_IN_SQOPERACAO)),0) POD_RE_QTDE_REAL_ANT,


										 --IDENTIFICA A SEQ. APONTAMENTO DA OPERAÇÃO ANTERIOR
										 NVL((SELECT MIN(APO.APO_IN_SEQUENCIA)
													FROM   MGMAN.PRO_PROG_ORDEM  POA,
																 MGMAN.PRO_APONTAORDEM APO
													WHERE  POA.ORG_TAB_IN_CODIGO = PO.ORG_TAB_IN_CODIGO
														 AND POA.ORG_PAD_IN_CODIGO = PO.ORG_PAD_IN_CODIGO
														 AND POA.ORG_IN_CODIGO     = PO.ORG_IN_CODIGO
														 AND POA.ORG_TAU_ST_CODIGO = PO.ORG_TAU_ST_CODIGO
														 AND POA.FIL_IN_CODIGO     = PO.FIL_IN_CODIGO
														 AND POA.ORD_TAB_IN_CODIGO = PO.ORD_TAB_IN_CODIGO
														 AND POA.ORD_SEQ_IN_CODIGO = PO.ORD_SEQ_IN_CODIGO
														 AND POA.ORD_IN_CODIGO     = PO.ORD_IN_CODIGO
														 AND POA.TMP_CH_APONTA     = 'S'

														 AND POA.ORG_TAB_IN_CODIGO = APO.ORG_TAB_IN_CODIGO
														 AND POA.ORG_PAD_IN_CODIGO = APO.ORG_PAD_IN_CODIGO
														 AND POA.ORG_IN_CODIGO     = APO.ORG_IN_CODIGO
														 AND POA.ORG_TAU_ST_CODIGO = APO.ORG_TAU_ST_CODIGO
														 AND POA.FIL_IN_CODIGO     = APO.FIL_IN_CODIGO
														 AND POA.ORD_TAB_IN_CODIGO = APO.ORD_TAB_IN_CODIGO
														 AND POA.ORD_SEQ_IN_CODIGO = APO.ORD_SEQ_IN_CODIGO
														 AND POA.ORD_IN_CODIGO     = APO.ORD_IN_CODIGO
														 AND POA.PLF_IN_SQOPERACAO = APO.PLF_IN_SQOPERACAO
														 AND POA.UNI_TAB_IN_CODIGO = APO.UNI_TAB_IN_CODIGO
														 AND POA.UNI_PAD_IN_CODIGO = APO.UNI_PAD_IN_CODIGO
														 AND POA.UNI_ST_UNIDADE    = APO.UNI_ST_UNIDADE

														 AND POA.PLF_IN_SQOPERACAO = (SELECT MAX(POA.PLF_IN_SQOPERACAO)
																													FROM   MGMAN.PRO_PROG_ORDEM POA
																													WHERE  POA.ORG_TAB_IN_CODIGO = PO.ORG_TAB_IN_CODIGO
																														 AND POA.ORG_PAD_IN_CODIGO = PO.ORG_PAD_IN_CODIGO
																														 AND POA.ORG_IN_CODIGO     = PO.ORG_IN_CODIGO
																														 AND POA.ORG_TAU_ST_CODIGO = PO.ORG_TAU_ST_CODIGO
																														 AND POA.FIL_IN_CODIGO     = PO.FIL_IN_CODIGO
																														 AND POA.ORD_TAB_IN_CODIGO = PO.ORD_TAB_IN_CODIGO
																														 AND POA.ORD_SEQ_IN_CODIGO = PO.ORD_SEQ_IN_CODIGO
																														 AND POA.ORD_IN_CODIGO     = PO.ORD_IN_CODIGO
																														 AND POA.TMP_CH_APONTA     = 'S'
																														 AND POA.PLF_IN_SQOPERACAO < PO.PLF_IN_SQOPERACAO)),0) APO_IN_SEQUENCIA_ANT,


										--IDENTIFICA A PRÓXIMA OPERAÇÃO
										 (SELECT MIN(POA.PLF_IN_SQOPERACAO)
											FROM   MGMAN.PRO_PROG_ORDEM POA
											WHERE  POA.ORG_TAB_IN_CODIGO = PO.ORG_TAB_IN_CODIGO
												 AND POA.ORG_PAD_IN_CODIGO = PO.ORG_PAD_IN_CODIGO
												 AND POA.ORG_IN_CODIGO     = PO.ORG_IN_CODIGO
												 AND POA.ORG_TAU_ST_CODIGO = PO.ORG_TAU_ST_CODIGO
												 AND POA.FIL_IN_CODIGO     = PO.FIL_IN_CODIGO
												 AND POA.ORD_TAB_IN_CODIGO = PO.ORD_TAB_IN_CODIGO
												 AND POA.ORD_SEQ_IN_CODIGO = PO.ORD_SEQ_IN_CODIGO
												 AND POA.ORD_IN_CODIGO     = PO.ORD_IN_CODIGO
												 AND POA.TMP_CH_APONTA     = 'S'
												 AND POA.PLF_IN_SQOPERACAO > PO.PLF_IN_SQOPERACAO) PLF_IN_SQOPERACAO_PROX,

										 --IDENTIFICA A QTDE REALIZADA NA PRÓXIMA OPERAÇÃO
										 NVL((SELECT SUM(APO.APO_RE_QUANTIDADE)
													FROM   MGMAN.PRO_PROG_ORDEM  POA,
																 MGMAN.PRO_APONTAORDEM APO
													WHERE  POA.ORG_TAB_IN_CODIGO = PO.ORG_TAB_IN_CODIGO
														 AND POA.ORG_PAD_IN_CODIGO = PO.ORG_PAD_IN_CODIGO
														 AND POA.ORG_IN_CODIGO     = PO.ORG_IN_CODIGO
														 AND POA.ORG_TAU_ST_CODIGO = PO.ORG_TAU_ST_CODIGO
														 AND POA.FIL_IN_CODIGO     = PO.FIL_IN_CODIGO
														 AND POA.ORD_TAB_IN_CODIGO = PO.ORD_TAB_IN_CODIGO
														 AND POA.ORD_SEQ_IN_CODIGO = PO.ORD_SEQ_IN_CODIGO
														 AND POA.ORD_IN_CODIGO     = PO.ORD_IN_CODIGO
														 AND POA.TMP_CH_APONTA     = 'S'

														 AND POA.ORG_TAB_IN_CODIGO = APO.ORG_TAB_IN_CODIGO
														 AND POA.ORG_PAD_IN_CODIGO = APO.ORG_PAD_IN_CODIGO
														 AND POA.ORG_IN_CODIGO     = APO.ORG_IN_CODIGO
														 AND POA.ORG_TAU_ST_CODIGO = APO.ORG_TAU_ST_CODIGO
														 AND POA.FIL_IN_CODIGO     = APO.FIL_IN_CODIGO
														 AND POA.ORD_TAB_IN_CODIGO = APO.ORD_TAB_IN_CODIGO
														 AND POA.ORD_SEQ_IN_CODIGO = APO.ORD_SEQ_IN_CODIGO
														 AND POA.ORD_IN_CODIGO     = APO.ORD_IN_CODIGO
														 AND POA.PLF_IN_SQOPERACAO = APO.PLF_IN_SQOPERACAO
														 AND POA.UNI_TAB_IN_CODIGO = APO.UNI_TAB_IN_CODIGO
														 AND POA.UNI_PAD_IN_CODIGO = APO.UNI_PAD_IN_CODIGO
														 AND POA.UNI_ST_UNIDADE    = APO.UNI_ST_UNIDADE

														 AND POA.PLF_IN_SQOPERACAO = (SELECT MIN(POA.PLF_IN_SQOPERACAO)
																													FROM   MGMAN.PRO_PROG_ORDEM POA
																													WHERE  POA.ORG_TAB_IN_CODIGO = PO.ORG_TAB_IN_CODIGO
																														 AND POA.ORG_PAD_IN_CODIGO = PO.ORG_PAD_IN_CODIGO
																														 AND POA.ORG_IN_CODIGO     = PO.ORG_IN_CODIGO
																														 AND POA.ORG_TAU_ST_CODIGO = PO.ORG_TAU_ST_CODIGO
																														 AND POA.FIL_IN_CODIGO     = PO.FIL_IN_CODIGO
																														 AND POA.ORD_TAB_IN_CODIGO = PO.ORD_TAB_IN_CODIGO
																														 AND POA.ORD_SEQ_IN_CODIGO = PO.ORD_SEQ_IN_CODIGO
																														 AND POA.ORD_IN_CODIGO     = PO.ORD_IN_CODIGO
																														 AND POA.TMP_CH_APONTA     = 'S'
																														 AND POA.PLF_IN_SQOPERACAO > PO.PLF_IN_SQOPERACAO)),0) POD_RE_QTDE_REAL_PROX,

										 --IDENTIFICA A QTDE DE REFUGO DA OPERAÇÃO
										 NVL((SELECT SUM(AO.APO_RE_QUANTIDADEREF)
													FROM   MGMAN.PRO_APONTAORDEM AO
													WHERE  AO.ORG_TAB_IN_CODIGO = PO.ORG_TAB_IN_CODIGO
														 AND AO.ORG_PAD_IN_CODIGO = PO.ORG_PAD_IN_CODIGO
														 AND AO.ORG_IN_CODIGO     = PO.ORG_IN_CODIGO
														 AND AO.ORG_TAU_ST_CODIGO = PO.ORG_TAU_ST_CODIGO
														 AND AO.FIL_IN_CODIGO     = PO.FIL_IN_CODIGO
														 AND AO.ORD_TAB_IN_CODIGO = PO.ORD_TAB_IN_CODIGO
														 AND AO.ORD_SEQ_IN_CODIGO = PO.ORD_SEQ_IN_CODIGO
														 AND AO.ORD_IN_CODIGO     = PO.ORD_IN_CODIGO
														 AND AO.PLF_IN_SQOPERACAO = PO.PLF_IN_SQOPERACAO),0) PLF_RE_QTDE_REFUGO,

										 --IDENTIFICA A QTDE DE INTERDITADA NA OPERAÇÃO (SUBPRODUTO)
										 NVL((SELECT SUM(OSP.OSP_RE_QTDE)
													FROM   MGMAN.PRO_APONTAORDEM  AO,
																 MGMAN.PRO_ORDEMSUBPROD OSP
													WHERE  AO.ORG_TAB_IN_CODIGO = PO.ORG_TAB_IN_CODIGO
														 AND AO.ORG_PAD_IN_CODIGO = PO.ORG_PAD_IN_CODIGO
														 AND AO.ORG_IN_CODIGO     = PO.ORG_IN_CODIGO
														 AND AO.ORG_TAU_ST_CODIGO = PO.ORG_TAU_ST_CODIGO
														 AND AO.FIL_IN_CODIGO     = PO.FIL_IN_CODIGO
														 AND AO.ORD_TAB_IN_CODIGO = PO.ORD_TAB_IN_CODIGO
														 AND AO.ORD_SEQ_IN_CODIGO = PO.ORD_SEQ_IN_CODIGO
														 AND AO.ORD_IN_CODIGO     = PO.ORD_IN_CODIGO
														 AND AO.PLF_IN_SQOPERACAO = PO.PLF_IN_SQOPERACAO
														 AND  AO.APO_IN_SEQUENCIA  = OSP.APO_IN_SEQUENCIA),0) PLF_RE_QTDE_SUBPROD,

										 --IDENTIFICA A QTDE DE INTERDITADA ACUMULADA ATÉ OPERAÇÃO (SUBPRODUTO)
										 NVL((SELECT SUM(OSP.OSP_RE_QTDE)
													FROM   MGMAN.PRO_APONTAORDEM  AO,
																 MGMAN.PRO_ORDEMSUBPROD OSP
													WHERE  AO.ORG_TAB_IN_CODIGO = PO.ORG_TAB_IN_CODIGO
														 AND AO.ORG_PAD_IN_CODIGO = PO.ORG_PAD_IN_CODIGO
														 AND AO.ORG_IN_CODIGO     = PO.ORG_IN_CODIGO
														 AND AO.ORG_TAU_ST_CODIGO = PO.ORG_TAU_ST_CODIGO
														 AND AO.FIL_IN_CODIGO     = PO.FIL_IN_CODIGO
														 AND AO.ORD_TAB_IN_CODIGO = PO.ORD_TAB_IN_CODIGO
														 AND AO.ORD_SEQ_IN_CODIGO = PO.ORD_SEQ_IN_CODIGO
														 AND AO.ORD_IN_CODIGO     = PO.ORD_IN_CODIGO
														 AND AO.PLF_IN_SQOPERACAO <= PO.PLF_IN_SQOPERACAO
														 AND  AO.APO_IN_SEQUENCIA  = OSP.APO_IN_SEQUENCIA),0) PLF_RE_QTDE_SUBPROD_ACUM,

										--IDENTIFICA A QTDE DE REFUGO ACUMULADO ATÉ A OPERAÇÃO
										 NVL((SELECT SUM(AO.APO_RE_QUANTIDADEREF)
													FROM   MGMAN.PRO_APONTAORDEM AO
													WHERE  AO.ORG_TAB_IN_CODIGO = PO.ORG_TAB_IN_CODIGO
														 AND AO.ORG_PAD_IN_CODIGO = PO.ORG_PAD_IN_CODIGO
														 AND AO.ORG_IN_CODIGO     = PO.ORG_IN_CODIGO
														 AND AO.ORG_TAU_ST_CODIGO = PO.ORG_TAU_ST_CODIGO
														 AND AO.FIL_IN_CODIGO     = PO.FIL_IN_CODIGO
														 AND AO.ORD_TAB_IN_CODIGO = PO.ORD_TAB_IN_CODIGO
														 AND AO.ORD_SEQ_IN_CODIGO = PO.ORD_SEQ_IN_CODIGO
														 AND AO.ORD_IN_CODIGO     = PO.ORD_IN_CODIGO
														 AND AO.PLF_IN_SQOPERACAO <= PO.PLF_IN_SQOPERACAO),0) PLF_RE_QTDE_REFUGO_ACUM,

										 --IDENTIFICA A PRIMEIRA OPERAÇÃO DA ORDEM
										 (SELECT MIN(POA.PLF_IN_SQOPERACAO)
											FROM   MGMAN.PRO_PROG_ORDEM POA
											WHERE  POA.ORG_TAB_IN_CODIGO = PO.ORG_TAB_IN_CODIGO
												 AND POA.ORG_PAD_IN_CODIGO = PO.ORG_PAD_IN_CODIGO
												 AND POA.ORG_IN_CODIGO     = PO.ORG_IN_CODIGO
												 AND POA.ORG_TAU_ST_CODIGO = PO.ORG_TAU_ST_CODIGO
												 AND POA.FIL_IN_CODIGO     = PO.FIL_IN_CODIGO
												 AND POA.ORD_TAB_IN_CODIGO = PO.ORD_TAB_IN_CODIGO
												 AND POA.ORD_SEQ_IN_CODIGO = PO.ORD_SEQ_IN_CODIGO
												 AND POA.ORD_IN_CODIGO     = PO.ORD_IN_CODIGO
												 AND POA.TMP_CH_APONTA     = 'S')    PLF_IN_SQOPERACAO_PRI,

										 --IDENTIFICA A ÚLTIMA OPERACAO DA ORDEM
										 (SELECT MAX(POA.PLF_IN_SQOPERACAO)
											FROM   MGMAN.PRO_PROG_ORDEM POA
											WHERE  POA.ORG_TAB_IN_CODIGO = PO.ORG_TAB_IN_CODIGO
												 AND POA.ORG_PAD_IN_CODIGO = PO.ORG_PAD_IN_CODIGO
												 AND POA.ORG_IN_CODIGO     = PO.ORG_IN_CODIGO
												 AND POA.ORG_TAU_ST_CODIGO = PO.ORG_TAU_ST_CODIGO
												 AND POA.FIL_IN_CODIGO     = PO.FIL_IN_CODIGO
												 AND POA.ORD_TAB_IN_CODIGO = PO.ORD_TAB_IN_CODIGO
												 AND POA.ORD_SEQ_IN_CODIGO = PO.ORD_SEQ_IN_CODIGO
												 AND POA.ORD_IN_CODIGO     = PO.ORD_IN_CODIGO
												 AND POA.TMP_CH_APONTA     = 'S')    PLF_IN_SQOPERACAO_ULT,

										 --SE ORDEM PAI, IDENTIFICA A QUANTIDADE RECEBIDA DA ORDEM FILHA
										 NVL((SELECT 'S'
													FROM   MGMAN.PRO_ORDENS ORDF
													WHERE  ORDF.ORG_TAB_IN_CODIGO = ORD.ORG_TAB_IN_CODIGO
														AND  ORDF.ORG_PAD_IN_CODIGO = ORD.ORG_PAD_IN_CODIGO
														AND  ORDF.ORG_IN_CODIGO     = ORD.ORG_IN_CODIGO
														AND  ORDF.ORG_TAU_ST_CODIGO = ORD.ORG_TAU_ST_CODIGO
														AND  ORDF.FIL_IN_CODIGO     = ORD.FIL_IN_CODIGO
														AND  ORDF.ORD_TAB_IN_CODIGO = ORD.ORD_TAB_IN_CODIGO
														AND  ORDF.ORD_SEQ_IN_CODIGO = ORD.ORD_SEQ_IN_CODIGO
														AND  ORDF.PAI_ORD_IN_CODIGO = ORD.ORD_IN_CODIGO
														AND  ROWNUM                 = 1),'N') ORD_BO_CONTEM_ORDEM_FILHA,

										 CASE
											 WHEN NVL((SELECT 'S'
																 FROM   MGMAN.PRO_ORDENS ORDF
																 WHERE  ORDF.ORG_TAB_IN_CODIGO = ORD.ORG_TAB_IN_CODIGO
																	 AND  ORDF.ORG_PAD_IN_CODIGO = ORD.ORG_PAD_IN_CODIGO
																	 AND  ORDF.ORG_IN_CODIGO     = ORD.ORG_IN_CODIGO
																	 AND  ORDF.ORG_TAU_ST_CODIGO = ORD.ORG_TAU_ST_CODIGO
																	 AND  ORDF.FIL_IN_CODIGO     = ORD.FIL_IN_CODIGO
																	 AND  ORDF.ORD_TAB_IN_CODIGO = ORD.ORD_TAB_IN_CODIGO
																	 AND  ORDF.ORD_SEQ_IN_CODIGO = ORD.ORD_SEQ_IN_CODIGO
																	 AND  ORDF.PAI_ORD_IN_CODIGO = ORD.ORD_IN_CODIGO
																	 AND  ROWNUM                 = 1),'N') = 'S' THEN
														--IDENTIFICA A QUANTIDADE RECEBIDA DA ORDEM FILHA
														NVL((SELECT SUM(ORDF.ORD_RE_QTDE_RECEBIDA)
																 FROM   MGMAN.PRO_ORDENS ORDF
																 WHERE  ORDF.ORG_TAB_IN_CODIGO = ORD.ORG_TAB_IN_CODIGO
																	 AND  ORDF.ORG_PAD_IN_CODIGO = ORD.ORG_PAD_IN_CODIGO
																	 AND  ORDF.ORG_IN_CODIGO     = ORD.ORG_IN_CODIGO
																	 AND  ORDF.ORG_TAU_ST_CODIGO = ORD.ORG_TAU_ST_CODIGO
																	 AND  ORDF.FIL_IN_CODIGO     = ORD.FIL_IN_CODIGO
																	 AND  ORDF.ORD_TAB_IN_CODIGO = ORD.ORD_TAB_IN_CODIGO
																	 AND  ORDF.ORD_SEQ_IN_CODIGO = ORD.ORD_SEQ_IN_CODIGO
																	 AND  ORDF.PAI_ORD_IN_CODIGO = ORD.ORD_IN_CODIGO),0)
											 ELSE 0

										 END ORD_RE_SALDO_OF,

										 PO.POD_DT_INICIOREAL,
										 PO.POD_DT_TERMINOREAL

							FROM   MGMAN.PRO_ORDENS         ORD,
							       MGMAN.PRO_ORDENSCMPESP   OCE,
										 MGMAN.PRO_PROG_ORDEM     PO,
										 MGCUSTOM.APT_PRO_MAQUINA CMAQ,
										 MGMAN.PRO_CELULA         CEL,
										 MGMAN.PRO_MAQUINA        MAQ,
										 MGMAN.PRO_PROCESSO       PRC,
										 MGMAN.PRO_TIPOORDENS     TPO

							WHERE  ORD.ORG_TAB_IN_CODIGO = PO.ORG_TAB_IN_CODIGO
								AND  ORD.ORG_PAD_IN_CODIGO = PO.ORG_PAD_IN_CODIGO
								AND  ORD.ORG_IN_CODIGO     = PO.ORG_IN_CODIGO
								AND  ORD.ORG_TAU_ST_CODIGO = PO.ORG_TAU_ST_CODIGO
								AND  ORD.FIL_IN_CODIGO     = PO.FIL_IN_CODIGO
								AND  ORD.ORD_TAB_IN_CODIGO = PO.ORD_TAB_IN_CODIGO
								AND  ORD.ORD_SEQ_IN_CODIGO = PO.ORD_SEQ_IN_CODIGO
								AND  ORD.ORD_IN_CODIGO     = PO.ORD_IN_CODIGO

								AND  PO.MAQ_TAB_IN_CODIGO  = CMAQ.MAQ_TAB_IN_CODIGO (+)
								AND  PO.MAQ_PAD_IN_CODIGO  = CMAQ.MAQ_PAD_IN_CODIGO (+)
								AND  PO.MAQ_IN_CODIGO      = CMAQ.MAQ_IN_CODIGO     (+)

								AND  PO.MAQ_TAB_IN_CODIGO  = MAQ.MAQ_TAB_IN_CODIGO (+)
								AND  PO.MAQ_PAD_IN_CODIGO  = MAQ.MAQ_PAD_IN_CODIGO (+)
								AND  PO.MAQ_IN_CODIGO      = MAQ.MAQ_IN_CODIGO     (+)

								AND  MAQ.CEL_TAB_IN_CODIGO = CEL.CEL_TAB_IN_CODIGO (+)
								AND  MAQ.CEL_PAD_IN_CODIGO = CEL.CEL_PAD_IN_CODIGO (+)
								AND  MAQ.CEL_IN_CODIGO     = CEL.CEL_IN_CODIGO     (+)

                AND  ORD.ORG_TAB_IN_CODIGO = OCE.ORG_TAB_IN_CODIGO (+)
								AND  ORD.ORG_PAD_IN_CODIGO = OCE.ORG_PAD_IN_CODIGO (+)
								AND  ORD.ORG_IN_CODIGO     = OCE.ORG_IN_CODIGO     (+)
								AND  ORD.ORG_TAU_ST_CODIGO = OCE.ORG_TAU_ST_CODIGO (+)
								AND  ORD.ORD_TAB_IN_CODIGO = OCE.ORD_TAB_IN_CODIGO (+)
								AND  ORD.ORD_SEQ_IN_CODIGO = OCE.ORD_SEQ_IN_CODIGO (+)
								AND  ORD.ORD_IN_CODIGO     = OCE.ORD_IN_CODIGO		 (+)

								AND  PO.PRC_TAB_IN_CODIGO  = PRC.PRC_TAB_IN_CODIGO (+)
								AND  PO.PRC_PAD_IN_CODIGO  = PRC.PRC_PAD_IN_CODIGO (+)
								AND  PO.PRC_IN_CODIGO      = PRC.PRC_IN_CODIGO     (+)

								AND  ORD.TPO_TAB_IN_CODIGO  = TPO.TPO_TAB_IN_CODIGO
								AND  ORD.TPO_PAD_IN_CODIGO  = TPO.TPO_PAD_IN_CODIGO
								AND  ORD.TPO_ST_CODIGO_TIPO = TPO.TPO_ST_CODIGO_TIPO

								AND  PO.ORG_TAB_IN_CODIGO = 53
								AND  PO.ORG_PAD_IN_CODIGO = 1
								AND  PO.ORG_TAU_ST_CODIGO = 'G'
								AND  PO.ORD_TAB_IN_CODIGO = 218
								AND  PO.TMP_CH_APONTA     = 'S'
								AND  PO.POD_ST_SITUACAO  <> 'EN'
								AND  PO.POD_ST_SITUACAO  <> 'CA'

								AND  ORD.ORD_ST_SITUACAO <> 'EN'
                AND  ORD.ORD_ST_SITUACAO <> 'CA'

							) SEQ

				WHERE SEQ.ORG_TAB_IN_CODIGO = ORD.ORG_TAB_IN_CODIGO
					AND SEQ.ORG_PAD_IN_CODIGO = ORD.ORG_PAD_IN_CODIGO
					AND SEQ.ORG_TAU_ST_CODIGO = ORD.ORG_TAU_ST_CODIGO
					AND SEQ.FIL_IN_CODIGO     = ORD.FIL_IN_CODIGO
					AND SEQ.ORD_TAB_IN_CODIGO = ORD.ORD_TAB_IN_CODIGO
					AND SEQ.ORD_SEQ_IN_CODIGO = ORD.ORD_SEQ_IN_CODIGO
					AND SEQ.ORD_IN_CODIGO_PAI = ORD.ORD_IN_CODIGO_PAI

					AND ORD.ORD_IN_CODIGO     = ORD.ORD_IN_CODIGO_PAI

					--CONTROLE DE SALDOS
					AND (

							 --PRIMEIRA OPERAÇÃO
							 (
								SEQ.PLF_IN_SQOPERACAO = SEQ.PLF_IN_SQOPERACAO_PRI AND
								(
								 --ORDEM SEM DEPENDÊNCIA
								 (SEQ.ORD_BO_CONTEM_ORDEM_FILHA = 'N' AND (SEQ.POD_RE_QTDENECESSARIA - (SEQ.POD_RE_QTDEREAL + SEQ.PLF_RE_QTDE_REFUGO_ACUM)) > 0)
								 OR
								 --ORDEM COM DEPENDÊNCIA
								 (SEQ.ORD_BO_CONTEM_ORDEM_FILHA = 'S' AND (SEQ.ORD_RE_SALDO_OF - (SEQ.POD_RE_QTDEREAL + SEQ.PLF_RE_QTDE_REFUGO_ACUM)) > 0)
								)
							)
							OR
							--OUTRAS OPERAÇÕES
							 (
								SEQ.PLF_IN_SQOPERACAO > SEQ.PLF_IN_SQOPERACAO_PRI AND
								(
								 ((SEQ.POD_RE_QTDE_REAL_ANT - (SEQ.POD_RE_QTDEREAL + SEQ.PLF_RE_QTDE_REFUGO_ACUM)) > 0)
								)
							 )
							OR (NVL(SEQ.CUS_BO_APTSALDO,'S') = 'S' AND (SEQ.POD_RE_QTDENECESSARIA - (SEQ.POD_RE_QTDEREAL + SEQ.PLF_RE_QTDE_REFUGO_ACUM)) > 0)
							)

				--PRIORIZAÇÃO DE ORDENS
				ORDER BY
					TO_NUMBER(TO_CHAR(ORD.ORD_DT_RECEBIMENTO,'IW')||TO_CHAR(ORD.ORD_DT_RECEBIMENTO,'YYYY')), /*ORD.ORD_DT_RECEBIMENTO,*/ ORD.ORD_IN_PRIORIDADE, SEQ.APO_IN_SEQUENCIA_ANT, SEQ.ORD_IN_CODIGO_PAI, SEQ.PLF_IN_SQOPERACAO
			 ) X
;
